#!/usr/bin/env python3

print("Welcome to the Calculator")
#Welcome Note

a = int(input("Enter the first variable\n"))
b = int(input("Enter the second variable\n"))
#input of variables

print("Operations:\n 1. Multiplication: X\n 2. Division \\ \n 3. Addition: +\n 4. Substraction: - \n Choose any of thes>z = input("Enter the operation to be performed\n")
#Iputting the operation

if(z==1):
  c = a*b
elif(z==2):
  c = a/b
elif(z==3):
  c = a+b
else:
  c = a-b
#if else for reading the operation and performing it


print("The Value of the operation is {}".format(c))
#To print the value
